trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  
container:
  image: 'cypress/browsers:22.16.0'
  
steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '18.12.0'
  displayName: 'Install Node.js 18.12.0'

- script: |
    npm ci
    npx cypress verify
  displayName: 'Install Cypress and verify'

- script: npm run test
  displayName: 'Run Cypress tests'
  continueOnError: 'true'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'cypress/Test-results.xml'
    testRunTitle: 'Test Results'
