name: Generate Cypress Report

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.16.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Verify Cypress install
        run: npx cypress verify

      - name: Run Cypress tests
        run: npm run test
