# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-action
name: Generate Cypress Report
on:
  workflow_dispatch:
    inputs:
      name:
         description: 'Person to greet'
         default: 'World'
         required: true
  push:
    branches:
      - 'main'

jobs:
  cypress-test:
    name: Run on Chrome 83
    runs-on: ubuntu-latest
    container: cypress/browsers:22.16.0
    steps:
      - uses: actions/checkout@v4

      - name: Install cypress and verify
        run: |
          npm ci
          $(npm bin)/cypress verify

      - name: Run Cypress tests
        run: npm run test
        continue-on-error: false
